### ISSUE TITLE
Multi-platform API client generation.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-api#2]
To start, we'd like to support:

 - Ruby
 - Python
 - PHP
 - Node

Eventually, we'd like to support the same platforms Stripe supports, which includes Java, Go, and .NET.

When a user runs:

```
rake bullet_train:generate_api_clients
```

## First Run Experience

If no `config/clients.yml` exists yet, ask them which clients they'd like to support. Also prompt the user for the root URL of their production environment, e.g. `https://api.collabhq.com`. We'll use that to calculate the location of their OpenAPI manifest.

For each client they want to support, we need them to spin up a public repository they can push the client library to. We do this by suggesting the logical name for the repository, sending them to `https://github.com/new`, and then asking them to paste the SSH URL of the resulting repository after they've created it.

We save all these details for the packages they've said they want to generate to the a configuration file at `config/clients.yml` that looks like this:

```
source: https://api.collabhq.com/api/swagger_doc.json
targets:
  ruby:
    repo: git@github.com:collab-hq/collab-hq-ruby.git
    package: collab_hq
    version: 1.0.0
  php:
    repo: git@github.com:collab-hq/collab-hq-php.git
    package: collab-hq/collab-hq
    version: 1.0.0
  node:
    repo: git@github.com:collab-hq/collab-hq-node.git
    package: @collab-hq/collab-hq
    version: 1.0.0
  python:
    repo: git@github.com:collab-hq/collab-hq-python.git
    package: collab_hq
    version: 1.0.0
```

From there, we should clone each of those repositories into `tmp/clients`.

Then, for each client library, we should generate the client library into that directory. If the client library generator doesn't also generate the corresponding package management package, we should do that as well.

## Secondary Run Experience

If `config/clients.yml` already exists, then clone all the repositories into `tmp/clients` again.

Regenerate all the client library code. If there are no changes, don't do anything else.

If there are changes in a client repository, Increment the version number both in the package repository and in the `config/clients.yml`.

## Publishing

Once the generation process has happened successfully, users should be able to run:

```
rake bullet_train:publish_api_clients
```

From that, we should publish the packages to the corresponding package management platform (e.g. Ruby Gems, Composer, npm, etc.)
